# Generated by Django 5.2.12 on 2026-03-11 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posizione', models.IntegerField(blank=True, null=True, verbose_name='Posizione')),
                ('punti', models.IntegerField(default=0, verbose_name='Punti')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=22, null=True)),
            ],
            options={
                'verbose_name': 'Classifica',
                'verbose_name_plural': 'Classifiche',
                'db_table': 'golf_ranking',
                'ordering': ['posizione'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colpi_giocati', models.IntegerField(blank=True, null=True, verbose_name='Colpi Giocati')),
                ('colpi_aggiuntivi', models.IntegerField(default=0, verbose_name='Colpi HCP')),
                ('par_giocatore', models.IntegerField(verbose_name='Par Giocatore')),
                ('terminato', models.BooleanField(default=False, verbose_name='Terminato')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=22, null=True)),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'db_table': 'golf_score',
                'ordering': ['hole__nr_buca'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('nr_giro', models.IntegerField(default=1, verbose_name='Nr. Giro')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=22, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Match',
                'db_table': 'golf_match',
                'ordering': ['-data', '-nr_giro'],
            },
        ),
    ]
