# Generated by Django 5.2.12 on 2026-03-11 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('courses', '0001_initial'),
        ('matches', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='golfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='users.golferprofile'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='matches.match'),
        ),
        migrations.AddField(
            model_name='score',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='score',
            name='golfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='users.golferprofile'),
        ),
        migrations.AddField(
            model_name='score',
            name='hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='courses.hole'),
        ),
        migrations.AddField(
            model_name='score',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='matches.match'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('club', 'data', 'nr_giro')},
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('match', 'golfer')},
        ),
    ]
