# Generated by Django 5.2.12 on 2026-03-11 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_buca', models.IntegerField(verbose_name='Buca')),
                ('denominazione', models.CharField(blank=True, default='', max_length=255, verbose_name='Denominazione')),
                ('descrizione', models.TextField(blank=True, default='', verbose_name='Descrizione')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('nr_colpi', models.IntegerField(verbose_name='Par')),
                ('distanza_t_rossi', models.IntegerField(blank=True, null=True, verbose_name='Distanza Tee Rossi')),
                ('distanza_t_gialli', models.IntegerField(blank=True, null=True, verbose_name='Distanza Tee Gialli')),
                ('hcp_buca', models.IntegerField(blank=True, null=True, verbose_name='Stroke Index')),
                ('img', models.ImageField(blank=True, null=True, upload_to='holes/', verbose_name='Immagine')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=22, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holes', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Buca',
                'verbose_name_plural': 'Buche',
                'db_table': 'golf_hole',
                'ordering': ['nr_buca'],
                'unique_together': {('club', 'nr_buca')},
            },
        ),
        migrations.CreateModel(
            name='HcpStrokeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcp', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Hcp')),
                ('da_hcp', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Da Hcp')),
                ('a_hcp', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='A Hcp')),
                ('colpi_aggiuntivi', models.IntegerField(default=0, verbose_name='Colpi Aggiuntivi')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=22, null=True)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hcp_allocations', to='courses.hole')),
            ],
            options={
                'verbose_name': 'Allocazione Colpi HCP',
                'verbose_name_plural': 'Allocazioni Colpi HCP',
                'db_table': 'golf_hcp_stroke_allocation',
            },
        ),
    ]
