# Generated by Django 5.2.12 on 2026-03-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(db_index=True, max_length=255, verbose_name='Ragione Sociale')),
                ('descrizione', models.TextField(blank=True, default='', verbose_name='Descrizione')),
                ('indirizzo', models.CharField(blank=True, default='', max_length=255, verbose_name='Indirizzo')),
                ('numero_civico', models.CharField(blank=True, default='', max_length=20, verbose_name='Numero Civico')),
                ('cap', models.CharField(blank=True, default='', max_length=5, verbose_name='CAP')),
                ('localita', models.CharField(blank=True, default='', max_length=255, verbose_name='Località')),
                ('provincia', models.CharField(blank=True, default='', max_length=2, verbose_name='Provincia')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('telefono', models.CharField(blank=True, default='', max_length=50, verbose_name='Telefono')),
                ('cellulare', models.CharField(blank=True, default='', max_length=50, verbose_name='Cellulare')),
                ('fax', models.CharField(blank=True, default='', max_length=50, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('pec', models.EmailField(blank=True, default='', max_length=254, verbose_name='PEC')),
                ('www', models.URLField(blank=True, default='', verbose_name='Internet')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs/', verbose_name='Logo')),
                ('hcp_max', models.IntegerField(blank=True, null=True, verbose_name='Hcp Max')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=22, null=True)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Club',
                'db_table': 'golf_club',
            },
        ),
    ]
